name = "Hugo ReFresh"
license = "MIT"
licenselink = "https://github.com/StefMa/hugo-fresh/blob/master/LICENSE.md"
description = "A Hugo re-adaptation of the Hugo Fresh theme"
homepage = "https://github.com/StefMa/hugo-fresh"
tags = ["responsive", "blog", "light", "clean", "personal"]
features = []
min_version = "0.45"

[author]
  name = "Roberto Jordaney"
  homepage = "https://github.com/StefMa"


# If porting an existing theme
[original]
    author = "Stefan M."
    homepage = "https://github.com/StefMa"
    repo = "https://github.com/StefMa/hugo-fresh"